### PR TITLE
Drop support for Node.js < 4

### PR DESCRIPTION
**Pull request by realityking**
Please double check the removal of `is-relative-path` the module behaves a little bit different than the native Node function.

### CODE REVIEW

**Comment by realityking** [comment]
@mrjoelkemp Did you overlook this one? No worries if it's a lack of time, just checking in.

**Comment by realityking** [comment]
@mrjoelkemp Could you have a look at this one? Thanks :)

**Comment by mrjoelkemp** [comment]
Thanks for the nudge here @realityking! Sorry I dropped the ball on this one. I just cut a new major version. I'll add it to filing cabinet too. Thanks again ❤️ .

**Comment by realityking** [comment]
No worries, life sometimes gets in the way :)

**Pull request merged**
